import PDFDocument from 'pdfkit';

export const generatePdf = async (data) =>
{
    return new Promise((resolve,reject) => {
        const doc = new PDFDocument({
            size: 'A4',
            margin: 50,
            info: {
                Title: data.title || 'Untitled Document',
                Author: "Shubh AI",
                Creator: "Shubh AI",
            }
        });

        const chunks = [];

        doc.on('data', (chunk) => {chunks.push(chunk)});
        doc.on('end', () => resolve(Buffer.concat(chunks)));
        doc.on('error', (err) => reject(err));

        // title
        doc
            .fontSize(28)
            .text(data.title, {align: 'center'})
            .fillColor('#111827')

        if(data.subtitle){
            doc.moveDown(0.5);
        }

        // subtitle
        doc
            .fontSize(20)
            .text(data.subtitle, {align: 'center'})
            .fillColor('#374151')

        doc.moveDown(2);

        // Sections
        data?.sections?.forEach(s => 
        {
            doc
            .fontSize(18)
            .text(s.heading, {align: 'left'})
            .fillColor('#111827')

            doc.moveDown(0.5);

            s.points.forEach((p) =>
            {
                doc
                .fontSize(14)
                .text(`• ${p}`, {align: 'left', lineGap: 4})
                .fillColor('#374151')
            })

            doc.moveDown(1.5);

             
        }
        )

        doc.moveDown(2);

        // Footer
        doc
        .fontSize(10)
        .text("Generated by Shubh AI", {align: 'center'})
        .fillColor('#9CA3AF')

        doc.end();



    })
}